In [ ]:
#CREAR ESTRUCTURA DE CARPETAS
!mkdir -p datos/crudos
!mkdir -p datos/procesados
!mkdir -p datos/externos

print('Carpetas creadas!!!!')

Carpetas creadas!!!!

In [ ]:
#IMPORTAR LIBRERIAS
import pandas as pd
import sqlite3
import json
from pathlib import Path

print('Librerias importadas')

Librerias importadas

In [ ]:
#DEFINIR RUTA DE TRABAJO
BASE_DIR = Path("/content/")
DATA_RAW = BASE_DIR / "datos"/"crudos"
DATA_PROCESSED = BASE_DIR / "datos"/"procesados"
DATA_EXTERNAL = BASE_DIR / "datos"/"externos"

print (f"Datos crudos: {DATA_RAW}")
print (f"Datos procesados: {DATA_PROCESSED}")
print (f"Datos externos: {DATA_EXTERNAL}")

Datos crudos: /content/datos/crudos
Datos procesados: /content/datos/procesados
Datos externos: /content/datos/externos

In [ ]:
# CREAR DATOS DE EMPLEADOS

empleados = pd.DataFrame({
    "id_empleado": [1,2,3,4,5,6,7,8,9,10],
    "nombre": ["Ana","Luis","Carlos","María","Sofía","José","Laura","Daniel","Paola","Miguel"],
    "departamento": ["Ventas","IT","Finanzas","RRHH","Marketing","IT","Ventas","Finanzas","RRHH","Marketing"],
    "edad": [25,31,28,35,29,26,40,33,27,38],
    "desempeño": [85,92,70,88,78,95,65,82,90,74],
    "salario": [550,900,650,750,700,950,600,800,720,680],
    "tiempo_empresa_anios": [2,5,1,7,3,2,10,6,2,8],
    "estado_empleado": ["Activo","Activo","Inactivo","Activo","Activo",
                        "Activo","Inactivo","Activo","Activo","Inactivo"]
})

print("Datos de empleados creados!!!!")
print(empleados)

Datos de empleados creados!!!!
   id_empleado  nombre departamento  edad  desempeño  salario  \
0            1     Ana       Ventas    25         85      550
1            2    Luis           IT    31         92      900
2            3  Carlos     Finanzas    28         70      650
3            4   María         RRHH    35         88      750
4            5   Sofía    Marketing    29         78      700
5            6    José           IT    26         95      950
6            7   Laura       Ventas    40         65      600
7            8  Daniel     Finanzas    33         82      800
8            9   Paola         RRHH    27         90      720
9           10  Miguel    Marketing    38         74      680

   tiempo_empresa_anios estado_empleado
0                     2          Activo
1                     5          Activo
2                     1        Inactivo
3                     7          Activo
4                     3          Activo
5                     2          Activo
6                    10        Inactivo
7                     6          Activo
8                     2          Activo
9                     8        Inactivo

In [ ]:
# CREAR ARCHIVO CSV
ruta_csv = DATA_RAW / "empleados.csv"
empleados.to_csv(ruta_csv, index=False, encoding="utf-8")

print(f"Archivo CSV guardado en: {ruta_csv}")

Archivo CSV guardado en: /content/datos/crudos/empleados.csv

In [ ]:
# LEER ARCHIVO CSV
df_empleados = pd.read_csv(ruta_csv)

print("Leyendo el archivo CSV")
print(df_empleados.head())

Leyendo el archivo CSV
   id_empleado  nombre departamento  edad  desempeño  salario  \
0            1     Ana       Ventas    25         85      550
1            2    Luis           IT    31         92      900
2            3  Carlos     Finanzas    28         70      650
3            4   María         RRHH    35         88      750
4            5   Sofía    Marketing    29         78      700

   tiempo_empresa_anios estado_empleado
0                     2          Activo
1                     5          Activo
2                     1        Inactivo
3                     7          Activo
4                     3          Activo

In [ ]:
# CREAR COLUMNA CALCULADA - SALARIO ANUAL = SALARIO MENSUAL * 12
df_empleados["salario_anual"] = df_empleados["salario"] * 12

print("Empleados con salario anual calculado:\n")
print(df_empleados[["id_empleado", "nombre", "salario", "salario_anual"]])

Empleados con salario anual calculado:

   id_empleado  nombre  salario  salario_anual
0            1     Ana      550           6600
1            2    Luis      900          10800
2            3  Carlos      650           7800
3            4   María      750           9000
4            5   Sofía      700           8400
5            6    José      950          11400
6            7   Laura      600           7200
7            8  Daniel      800           9600
8            9   Paola      720           8640
9           10  Miguel      680           8160

In [ ]:
# CREAR BASE DE DATOS SQL - CONECTAMOS A SQLITE
conexion = sqlite3.connect(DATA_RAW / "empresa_hr_analytics.db")
cursor = conexion.cursor()
print("Base de datos conectada")

Base de datos conectada

In [ ]:
# CREAR TABLA CAPACITACIONES
cursor.execute("""
CREATE TABLE IF NOT EXISTS capacitaciones (
    id_capacitacion INTEGER PRIMARY KEY,
    id_empleado INTEGER NOT NULL,
    curso TEXT NOT NULL,
    horas INTEGER NOT NULL,
    resultado TEXT NOT NULL
)
""")

conexion.commit()

print("Tabla 'capacitaciones' creada")

Tabla 'capacitaciones' creada

In [ ]:
# INSERTAR CAPACITACIONES
capacitaciones = [
    (1, 1, "Excel avanzado", 10, "Aprobado"),
    (2, 2, "Comunicación efectiva", 8, "Aprobado"),
    (3, 3, "Liderazgo", 12, "Reprobado"),
    (4, 4, "Trabajo en equipo", 6, "Aprobado"),
    (5, 5, "Power BI", 10, "Aprobado"),
    (6, 6, "Gestión del tiempo", 6, "Aprobado"),
    (7, 7, "Resolución de conflictos", 8, "Reprobado"),
    (8, 8, "Inteligencia emocional", 8, "Aprobado"),
    (9, 9, "Análisis de datos", 12, "Aprobado"),
    (10, 10, "Seguridad informática", 10, "Aprobado")
]

cursor.executemany("""
INSERT OR REPLACE INTO capacitaciones
(id_capacitacion, id_empleado, curso, horas, resultado)
VALUES (?, ?, ?, ?, ?)
""", capacitaciones)

conexion.commit()

print("10 capacitaciones insertadas")

10 capacitaciones insertadas

In [ ]:
# CONSULTAR CAPACITACIONES
df_capacitaciones = pd.read_sql_query("SELECT * FROM capacitaciones;",conexion)

print("\nCapacitaciones en la base de datos\n")
df_capacitaciones

Capacitaciones en la base de datos

   id_capacitacion  id_empleado                     curso  horas  resultado
0                1            1            Excel avanzado     10   Aprobado
1                2            2     Comunicación efectiva      8   Aprobado
2                3            3                 Liderazgo     12  Reprobado
3                4            4         Trabajo en equipo      6   Aprobado
4                5            5                  Power BI     10   Aprobado
5                6            6        Gestión del tiempo      6   Aprobado
6                7            7  Resolución de conflictos      8  Reprobado
7                8            8    Inteligencia emocional      8   Aprobado
8                9            9         Análisis de datos     12   Aprobado
9               10           10     Seguridad informática     10   Aprobado

In [ ]:
# INTEGRAR EMPLEADOS + CAPACITACIONES
df_integrado = pd.merge(df_empleados, df_capacitaciones, on="id_empleado",how="left")

print("Empleados con información de capacitaciones\n")
df_integrado[["id_empleado", "nombre", "departamento", "desempeño","curso", "horas", "resultado"]]

Empleados con información de capacitaciones

,id_empleado,nombre,departamento,desempeño,curso,horas,resultado
0,1,Ana,Ventas,85,Excel avanzado,10,Aprobado
1,2,Luis,IT,92,Comunicación efectiva,8,Aprobado
2,3,Carlos,Finanzas,70,Liderazgo,12,Reprobado
3,4,María,RRHH,88,Trabajo en equipo,6,Aprobado
4,5,Sofía,Marketing,78,Power BI,10,Aprobado
5,6,José,IT,95,Gestión del tiempo,6,Aprobado
6,7,Laura,Ventas,65,Resolución de conflictos,8,Reprobado
7,8,Daniel,Finanzas,82,Inteligencia emocional,8,Aprobado
8,9,Paola,RRHH,90,Análisis de datos,12,Aprobado
9,10,Miguel,Marketing,74,Seguridad informática,10,Aprobado

In [ ]:
# CALCULAR INDICADOR - HORAS DE CAPACITACION POR EMPLEADO
df_integrado["horas_capacitacion"] = df_integrado["horas"]

print("\nEmpleados con horas de capacitación:")
df_integrado[["id_empleado", "nombre", "horas_capacitacion"]]

Empleados con horas de capacitación:

   id_empleado  nombre  horas_capacitacion
0            1     Ana                  10
1            2    Luis                   8
2            3  Carlos                  12
3            4   María                   6
4            5   Sofía                  10
5            6    José                   6
6            7   Laura                   8
7            8  Daniel                   8
8            9   Paola                  12
9           10  Miguel                  10

In [ ]:
# CREAR ARCHIVO JSON
datos_adicionales = [
    {"id_empleado": 1, "satisfaccion": 4, "horas_extra": 5},
    {"id_empleado": 2, "satisfaccion": 5, "horas_extra": 3},
    {"id_empleado": 3, "satisfaccion": 2, "horas_extra": 12},
    {"id_empleado": 4, "satisfaccion": 4, "horas_extra": 4},
    {"id_empleado": 5, "satisfaccion": 3, "horas_extra": 8},
    {"id_empleado": 6, "satisfaccion": 5, "horas_extra": 2},
    {"id_empleado": 7, "satisfaccion": 2, "horas_extra": 14},
    {"id_empleado": 8, "satisfaccion": 4, "horas_extra": 5},
    {"id_empleado": 9, "satisfaccion": 5, "horas_extra": 3},
    {"id_empleado": 10, "satisfaccion": 3, "horas_extra": 9}
]

print("Datos adicionales de empleados:")
for dato in datos_adicionales:
    print(f" Empleado {dato['id_empleado']}: satisfacción {dato['satisfaccion']} y horas extra: {dato['horas_extra']}")

Datos adicionales de empleados:
 Empleado 1: satisfacción 4 y horas extra: 5
 Empleado 2: satisfacción 5 y horas extra: 3
 Empleado 3: satisfacción 2 y horas extra: 12
 Empleado 4: satisfacción 4 y horas extra: 4
 Empleado 5: satisfacción 3 y horas extra: 8
 Empleado 6: satisfacción 5 y horas extra: 2
 Empleado 7: satisfacción 2 y horas extra: 14
 Empleado 8: satisfacción 4 y horas extra: 5
 Empleado 9: satisfacción 5 y horas extra: 3
 Empleado 10: satisfacción 3 y horas extra: 9

In [ ]:
# GUARDAR JSON

ruta_json = DATA_EXTERNAL / "datos_adicionales.json"
with open(ruta_json, "w", encoding="utf-8") as archivo:
    json.dump(datos_adicionales, archivo, ensure_ascii=False, indent=4)

print(f"Archivo JSON guardado en: {ruta_json}")

Archivo JSON guardado en: /content/datos/externos/datos_adicionales.json

In [ ]:
# LEER JSON
df_laborales = pd.read_json(ruta_json)

print("Datos adicionales como DataFrame")
df_laborales

Datos adicionales como DataFrame

   id_empleado  satisfaccion  horas_extra
0            1             4            5
1            2             5            3
2            3             2           12
3            4             4            4
4            5             3            8
5            6             5            2
6            7             2           14
7            8             4            5
8            9             5            3
9           10             3            9

In [ ]:
# INTEGRAR DATOS DEL JSON
df_final = pd.merge(df_integrado, df_laborales, on="id_empleado", how="left")

print("\nDataset final con información de las tres fuentes:")

df_final[["id_empleado", "nombre", "departamento", "desempeño", "horas_capacitacion", "satisfaccion", "horas_extra", "estado_empleado"]]

Dataset final con información de las tres fuentes:

,id_empleado,nombre,departamento,desempeño,horas_capacitacion,satisfaccion,horas_extra,estado_empleado
0,1,Ana,Ventas,85,10,4,5,Activo
1,2,Luis,IT,92,8,5,3,Activo
2,3,Carlos,Finanzas,70,12,2,12,Inactivo
3,4,María,RRHH,88,6,4,4,Activo
4,5,Sofía,Marketing,78,10,3,8,Activo
5,6,José,IT,95,6,5,2,Activo
6,7,Laura,Ventas,65,8,2,14,Inactivo
7,8,Daniel,Finanzas,82,8,4,5,Activo
8,9,Paola,RRHH,90,12,5,3,Activo
9,10,Miguel,Marketing,74,10,3,9,Inactivo

In [ ]:
# VALIDACIÓN DE CARDINALIDAD

filas_antes = len(df_integrado)
filas_despues = len(df_final)

columnas_antes = len(df_integrado.columns)
columnas_despues = len(df_final.columns)

duplicados_antes = df_integrado.duplicated().sum()
duplicados_despues = df_final.duplicated().sum()

print("VALIDACIÓN DE CARDINALIDAD")
print("Filas antes:", filas_antes)
print("Filas después:", filas_despues)
print("Columnas antes:", columnas_antes)
print("Columnas después:", columnas_despues)
print("Duplicados antes:", duplicados_antes)
print("Duplicados después:", duplicados_despues)

VALIDACIÓN DE CARDINALIDAD
Filas antes: 10
Filas después: 10
Columnas antes: 14
Columnas después: 16
Duplicados antes: 0
Duplicados después: 0

In [ ]:
# VALORES NULOS

print("VALORES NULOS: ")

nulos = df_final.isnull().sum()

print(nulos)

VALORES NULOS:
id_empleado             0
nombre                  0
departamento            0
edad                    0
desempeño               0
salario                 0
tiempo_empresa_anios    0
estado_empleado         0
salario_anual           0
id_capacitacion         0
curso                   0
horas                   0
resultado               0
horas_capacitacion      0
satisfaccion            0
horas_extra             0
dtype: int64

In [ ]:
# EVALUAR DUPLICADOS
print("Cantidad de filas duplicadas:")
duplicados = df_final.duplicated().sum()
print(f"Resgistros duplicados: {duplicados}")

Cantidad de filas duplicadas:
Resgistros duplicados: 0

In [ ]:
# REVISAR TIPOS DE DATOS
print("Tipos de datos:")
print(df_final.dtypes)

Tipos de datos:
id_empleado              int64
nombre                  object
departamento            object
edad                     int64
desempeño                int64
salario                  int64
tiempo_empresa_anios     int64
estado_empleado         object
salario_anual            int64
id_capacitacion          int64
curso                   object
horas                    int64
resultado               object
horas_capacitacion       int64
satisfaccion             int64
horas_extra              int64
dtype: object

In [ ]:
# CALCULAR TRES INDICADORES INICIALES

total_empleados = len(df_final)
empleados_inactivos = (df_final["estado_empleado"] == "Inactivo").sum()

porcentaje_inactivos = (empleados_inactivos / total_empleados) * 100
promedio_desempeño = df_final["desempeño"].mean()
promedio_satisfaccion = df_final["satisfaccion"].mean()

print("Indicadores iniciales:")
print("Porcentaje de empleados inactivos:", porcentaje_inactivos)
print("Promedio de desempeño:", promedio_desempeño)
print("Promedio de satisfacción:", promedio_satisfaccion)

Indicadores iniciales:
Porcentaje de empleados inactivos: 30.0
Promedio de desempeño: 81.9
Promedio de satisfacción: 3.7

In [ ]:
# CREAR INVENTARIO DE FUENTES
inventario_fuentes = pd.DataFrame({
    "fuente": ["Empleados", "Capacitaciones", "Datos adicionales"],
    "tipo": ["CSV", "SQL", "JSON"],
    "ubicacion": [
        "datos/crudos/empleados.csv",
        "datos/crudos/empresa_hr_analytics.db",
        "datos/externos/datos_adicionales.json"
    ],
    "descripcion": [
        "Datos generales y desempeño de empleados",
        "Información de cursos y horas de capacitación",
        "Satisfacción y horas extra"
    ]
})

print("Inventario de fuentes:")
print(inventario_fuentes)

Inventario de fuentes:
              fuente  tipo                              ubicacion  \
0          Empleados   CSV             datos/crudos/empleados.csv
1     Capacitaciones   SQL   datos/crudos/empresa_hr_analytics.db
2  Datos adicionales  JSON  datos/externos/datos_adicionales.json

                                     descripcion
0       Datos generales y desempeño de empleados
1  Información de cursos y horas de capacitación
2                     Satisfacción y horas extra

In [ ]:
# GUARDAR DATASET FINAL
df_final.to_csv(DATA_PROCESSED/"dataset_integrado_HRTech_People_Analytics.csv", index=False)

print(f" Dataset guardado en: {DATA_PROCESSED / 'dataset_integrado_HRTech_People_Analytics.csv'}")

print("Archivos generados")
print("datos/crudos: ")
!ls -la datos/crudos/

print("datos/externos: ")
!ls -la datos/externos/

print("datos/procesados: ")
!ls -la datos/procesados/

 Dataset guardado en: /content/datos/procesados/dataset_integrado_HRTech_People_Analytics.csv
Archivos generados
datos/crudos:
total 20
drwxr-xr-x 2 root root 4096 Sep 22 06:35 .
drwxr-xr-x 5 root root 4096 Sep 22 06:25 ..
-rw-r--r-- 1 root root  441 Sep 22 06:35 empleados.csv
-rw-r--r-- 1 root root 8192 Sep 22 06:35 empresa_hr_analytics.db
datos/externos:
total 12
drwxr-xr-x 2 root root 4096 Sep 22 06:35 .
drwxr-xr-x 5 root root 4096 Sep 22 06:25 ..
-rw-r--r-- 1 root root  915 Sep 22 06:35 datos_adicionales.json
datos/procesados:
total 12
drwxr-xr-x 2 root root 4096 Sep 22 06:35 .
drwxr-xr-x 5 root root 4096 Sep 22 06:25 ..
-rw-r--r-- 1 root root  980 Sep 22 06:35 dataset_integrado_HRTech_People_Analytics.csv

In [ ]:
# GUARDAR INDICADORES

indicadores = pd.DataFrame({
    "indicador": [
        "Porcentaje de empleados inactivos (%)",
        "Promedio de desempeño",
        "Promedio de satisfacción"
    ],
    "valor": [
        porcentaje_inactivos,
        promedio_desempeño,
        promedio_satisfaccion
    ]
})

ruta_indicadores = DATA_PROCESSED / "indicadores_iniciales.csv"
indicadores.to_csv(ruta_indicadores, index=False)

print("Indicadores guardados en:", ruta_indicadores)

Indicadores guardados en: /content/datos/procesados/indicadores_iniciales.csv

In [ ]:
# DESCARGAR ARCHIVO
from google.colab import files

files.download("/content/datos/procesados/dataset_integrado_HRTech_People_Analytics.csv")

print("Archivo descargado")

Archivo descargado

In [ ]:
print("----- Guia 02 -----")

----- Guia 02 -----

In [ ]:
import numpy as np
print("----- Libreria Importada -----")

----- Libreria Importada -----

In [ ]:
#DEFINIR RUTAS - MANTENEMOS LA MISMA ESTRUCTURA
BASE_DIR = Path("/content/")
DATA_PROCESSED = BASE_DIR/"datos"/"procesados"
DOCUMENTOS = BASE_DIR/"documentos"

#CREAR CARPETAS SI NO EXISTEN
DATA_PROCESSED.mkdir(parents=True, exist_ok=True)
DOCUMENTOS.mkdir(parents=True, exist_ok=True)

print(f"Datos procesados: {DATA_PROCESSED}")
print(f"Documentos: {DOCUMENTOS}")

Datos procesados: /content/datos/procesados
Documentos: /content/documentos

In [ ]:
#CARGAR DATASET DE LA GUIA 1
ruta_entrada = DATA_PROCESSED / "dataset_integrado_HRTech_People_Analytics.csv"
df = pd.read_csv(ruta_entrada)

print(f"Dataset cargado: {ruta_entrada}")
print(f"Dimensiones:  {df.shape[0]} filas, {df.shape[1]} columnas")

df.head()

Dataset cargado: /content/datos/procesados/dataset_integrado_HRTech_People_Analytics.csv
Dimensiones:  10 filas, 16 columnas

,id_empleado,nombre,departamento,edad,desempeño,salario,tiempo_empresa_anios,estado_empleado,salario_anual,id_capacitacion,curso,horas,resultado,horas_capacitacion,satisfaccion,horas_extra
0,1,Ana,Ventas,25,85,550,2,Activo,6600,1,Excel avanzado,10,Aprobado,10,4,5
1,2,Luis,IT,31,92,900,5,Activo,10800,2,Comunicación efectiva,8,Aprobado,8,5,3
2,3,Carlos,Finanzas,28,70,650,1,Inactivo,7800,3,Liderazgo,12,Reprobado,12,2,12
3,4,María,RRHH,35,88,750,7,Activo,9000,4,Trabajo en equipo,6,Aprobado,6,4,4
4,5,Sofía,Marketing,29,78,700,3,Activo,8400,5,Power BI,10,Aprobado,10,3,8

In [ ]:
#CREAR COPIAS DE TRABAJO - PARA NO PERDER EL ORIGINAL

df_original = df.copy() #Copia inalterada para compara después
df_limpio = df.copy() #Copia que vamos a modificar

print("Copias de trabajo creadas: -------")
print(f"Dataset original: {df_original.shape}")
print(f"Para limpiar:  {df_limpio.shape}")

Copias de trabajo creadas: -------
Dataset original: (10, 16)
Para limpiar:  (10, 16)

In [ ]:
#DIAGNOSTICO INICIAL DE CALIDAD

#DIMENSIONES - ¿CUANTOS DATOS TENEMOS?
print("Dimensiones: ------")
print(f"Filas: {df_limpio.shape[0]}, Columnas: {df_limpio.shape[1]}\n")

#NOMBRES DE COLUMNAS - ¿ESTÁN BIEN ESCRITOS?
print("Nombres de las columnas: ------")
print(df_limpio.columns.tolist())

Dimensiones: ------
Filas: 10, Columnas: 16

Nombres de las columnas: ------
['id_empleado', 'nombre', 'departamento', 'edad', 'desempeño', 'salario', 'tiempo_empresa_anios', 'estado_empleado', 'salario_anual', 'id_capacitacion', 'curso', 'horas', 'resultado', 'horas_capacitacion', 'satisfaccion', 'horas_extra']

In [ ]:
#TIPOS DE DATOS - ¿CADA COLUMNA TIENE EL TIPO CORRECTO?

print("\nTipos de datos: --------")
print(df_limpio.dtypes)

Tipos de datos: --------
id_empleado              int64
nombre                  object
departamento            object
edad                     int64
desempeño                int64
salario                  int64
tiempo_empresa_anios     int64
estado_empleado         object
salario_anual            int64
id_capacitacion          int64
curso                   object
horas                    int64
resultado               object
horas_capacitacion       int64
satisfaccion             int64
horas_extra              int64
dtype: object

In [ ]:
#INFORMACIÓN GENERAL - RESUMEN COMPLETO

print("Información General: --------")
df_limpio.info()

Información General: --------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id_empleado           10 non-null     int64
 1   nombre                10 non-null     object
 2   departamento          10 non-null     object
 3   edad                  10 non-null     int64
 4   desempeño             10 non-null     int64
 5   salario               10 non-null     int64
 6   tiempo_empresa_anios  10 non-null     int64
 7   estado_empleado       10 non-null     object
 8   salario_anual         10 non-null     int64
 9   id_capacitacion       10 non-null     int64
 10  curso                 10 non-null     object
 11  horas                 10 non-null     int64
 12  resultado             10 non-null     object
 13  horas_capacitacion    10 non-null     int64
 14  satisfaccion          10 non-null     int64
 15  horas_extra           10 non-null     int64
dtypes: int64(11), object(5)
memory usage: 1.4+ KB

In [ ]:
#VALORES NULOS - ¿HAY DATOS FALTANTES?

print("\nVALORES NULOS: ----------")
nulos = df_limpio.isnull().sum()
print(nulos)

#PORCENTAJES DE NULOS
print("\nPorcentajes de nulos: --------")
porcentaje_nulos = (df_limpio.isnull().mean() * 100).round(2)
print(porcentaje_nulos)

VALORES NULOS: ----------
id_empleado             0
nombre                  0
departamento            0
edad                    0
desempeño               0
salario                 0
tiempo_empresa_anios    0
estado_empleado         0
salario_anual           0
id_capacitacion         0
curso                   0
horas                   0
resultado               0
horas_capacitacion      0
satisfaccion            0
horas_extra             0
dtype: int64

Porcentajes de nulos: --------
id_empleado             0.0
nombre                  0.0
departamento            0.0
edad                    0.0
desempeño               0.0
salario                 0.0
tiempo_empresa_anios    0.0
estado_empleado         0.0
salario_anual           0.0
id_capacitacion         0.0
curso                   0.0
horas                   0.0
resultado               0.0
horas_capacitacion      0.0
satisfaccion            0.0
horas_extra             0.0
dtype: float64

In [ ]:
#REGISTROS DUPLICADOS - ¿HAY FILAS REPETIDAS?

print("Registros duplicados: ---------")

duplicados = df_limpio.duplicated().sum()
print(f"Registros duplicadas: {duplicados}")

Registros duplicados: ---------
Registros duplicadas: 0

In [ ]:
#VALORES UNICOS EN CATEGORIAS - ¿ESTAN CONSISTENTES?

print("Valores únicos en categorías: --------")
columnas_categorias = df_limpio.select_dtypes(include='object').columns

for columna in columnas_categorias:
    print(f"\n{columna}: ")
    print(df_limpio[columna].unique())

Valores únicos en categorías: --------

nombre:
['Ana' 'Luis' 'Carlos' 'María' 'Sofía' 'José' 'Laura' 'Daniel' 'Paola'
 'Miguel']

departamento:
['Ventas' 'IT' 'Finanzas' 'RRHH' 'Marketing']

estado_empleado:
['Activo' 'Inactivo']

curso:
['Excel avanzado' 'Comunicación efectiva' 'Liderazgo' 'Trabajo en equipo'
 'Power BI' 'Gestión del tiempo' 'Resolución de conflictos'
 'Inteligencia emocional' 'Análisis de datos' 'Seguridad informática']

resultado:
['Aprobado' 'Reprobado']

In [ ]:
# CREAR DATASET CON ERRORES CONTROLADOS
# SIMULACIÓN DE PROBLEMAS REALES EN EL DATASET DE EMPLEADOS

df_errores = df_limpio.copy()

# ERROR 1: Espacios y mayúsculas/minúsculas en departamento
df_errores.loc[0, 'departamento'] = ' ventas '   # Espacios al inicio y al final
df_errores.loc[1, 'departamento'] = 'it'         # En minúsculas
df_errores.loc[4, 'departamento'] = 'MARKETING ' # Mayúsculas con espacio

# ERROR 2: Valor nulo en una columna categórica o de métrica
df_errores.loc[3, 'resultado'] = np.nan

# ERROR 3: Salario negativo (dato numérico inválido)
df_errores.loc[2, 'salario'] = -650

# ERROR 4: Registro duplicado (repetir la primera fila)
df_errores = pd.concat([df_errores, df_errores.iloc[[0]]], ignore_index=True)

print("----- DATASET CON ERRORES -----")
print(df_errores[['id_empleado', 'nombre', 'departamento', 'salario', 'resultado']])

----- DATASET CON ERRORES -----
    id_empleado  nombre departamento  salario  resultado
0             1     Ana      ventas       550   Aprobado
1             2    Luis           it      900   Aprobado
2             3  Carlos     Finanzas     -650  Reprobado
3             4   María         RRHH      750        NaN
4             5   Sofía   MARKETING       700   Aprobado
5             6    José           IT      950   Aprobado
6             7   Laura       Ventas      600  Reprobado
7             8  Daniel     Finanzas      800   Aprobado
8             9   Paola         RRHH      720   Aprobado
9            10  Miguel    Marketing      680   Aprobado
10            1     Ana      ventas       550   Aprobado

In [ ]:
#GUARDAR EL DATASET CON ERRORES
ruta_errores = DATA_PROCESSED/"dataset_con_errores_HRTech_People_Analytics.csv"

df_errores.to_csv(ruta_errores, index=False, encoding='utf-8')
print(f"Dataset con errores guardado en: {ruta_errores}")

df_limpio = df_errores.copy()

Dataset con errores guardado en: /content/datos/procesados/dataset_con_errores_HRTech_People_Analytics.csv

In [ ]:
#LIMPIEZA DE NOMBRES D ECOLUMNAS
print("Nombres de columnas - antes: ")
print(df_limpio.columns.tolist())

df_limpio.columns = (
    df_limpio.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_', regex=False)
)
print("\nNombres de columnas - después: ")
print(df_limpio.columns.tolist())

Nombres de columnas - antes:
['id_empleado', 'nombre', 'departamento', 'edad', 'desempeño', 'salario', 'tiempo_empresa_anios', 'estado_empleado', 'salario_anual', 'id_capacitacion', 'curso', 'horas', 'resultado', 'horas_capacitacion', 'satisfaccion', 'horas_extra']

Nombres de columnas - después:
['id_empleado', 'nombre', 'departamento', 'edad', 'desempeño', 'salario', 'tiempo_empresa_anios', 'estado_empleado', 'salario_anual', 'id_capacitacion', 'curso', 'horas', 'resultado', 'horas_capacitacion', 'satisfaccion', 'horas_extra']

In [ ]:
#ELIMINAR ESPACIOS EN TEXTOS

#TODAS LAS COLUMNAS DE TEXTO DEBEN TENER SUS VALORES LIMPIOS
columnas_texto = df_limpio.select_dtypes(include='object').columns
print(f"Columnas de texto: {columnas_texto.tolist()}")

for columna in columnas_texto:
    df_limpio[columna] = df_limpio[columna].astype('string').str.strip()

    print("Espacios eliminados de las columnas de texto")

Columnas de texto: ['nombre', 'departamento', 'estado_empleado', 'curso', 'resultado']
Espacios eliminados de las columnas de texto
Espacios eliminados de las columnas de texto
Espacios eliminados de las columnas de texto
Espacios eliminados de las columnas de texto
Espacios eliminados de las columnas de texto

In [ ]:
# NORMALIZAR DEPARTAMENTO

print("DEPARTAMENTO - ANTES: ", df_limpio['departamento'].unique().tolist())

# CONVERTIR A MINÚSCULAS PRIMERO Y QUITAR ESPACIOS RESIDUALES
df_limpio['departamento'] = df_limpio['departamento'].astype(str).str.strip().str.lower()

# DICCIONARIO DE ESTANDARIZACIÓN
mapeo_departamentos = {
    'ventas': 'Ventas',
    'it': 'IT',
    'finanzas': 'Finanzas',
    'rrhh': 'RRHH',
    'marketing': 'Marketing'
}

df_limpio['departamento'] = df_limpio['departamento'].replace(mapeo_departamentos)

print("DEPARTAMENTO - DESPUÉS: ", df_limpio['departamento'].unique().tolist())

DEPARTAMENTO - ANTES:  ['ventas', 'it', 'Finanzas', 'RRHH', 'MARKETING', 'IT', 'Ventas', 'Marketing']
DEPARTAMENTO - DESPUÉS:  ['Ventas', 'IT', 'Finanzas', 'RRHH', 'Marketing']

In [ ]:
# NORMALIZAR CATEGORIAS PRINCIPALES
# ESTANDARIZAR FORMATO DE DEPARTAMENTO, CURSO, RESULTADO Y ESTADO DEL EMPLEADO

columnas_normalizar = ['departamento', 'curso', 'resultado', 'estado_empleado']

for columna in columnas_normalizar:
    if columna in df_limpio.columns:
        df_limpio[columna] = (
            df_limpio[columna]
            .astype('string')
            .str.strip()
            .str.title()
        )

        if columna == 'departamento':
            df_limpio[columna] = df_limpio[columna].replace({
                'It': 'IT',
                'Rrhh': 'RRHH'
            })

        print(f"{columna} normalizada: {df_limpio[columna].unique().tolist()}")

departamento normalizada: ['Ventas', 'IT', 'Finanzas', 'RRHH', 'Marketing']
curso normalizada: ['Excel Avanzado', 'Comunicación Efectiva', 'Liderazgo', 'Trabajo En Equipo', 'Power Bi', 'Gestión Del Tiempo', 'Resolución De Conflictos', 'Inteligencia Emocional', 'Análisis De Datos', 'Seguridad Informática']
resultado normalizada: ['Aprobado', 'Reprobado', <NA>]
estado_empleado normalizada: ['Activo', 'Inactivo']

In [ ]:
#RESTAURAR VALORES NULOS

df_limpio = df_limpio.replace({'nan': np.nan, '<NA>': np.nan, 'None': np.nan})

print("VALORES NULOS DESPUÉS DE RESTAURAR: ------------")

print(df_limpio[['resultado']].isnull().sum())

VALORES NULOS DESPUÉS DE RESTAURAR: ------------
resultado    1
dtype: int64

In [ ]:
#COMPLETAR VALORES AUSENTES

df_limpio['curso'] = df_limpio['curso'].fillna('Sin curso asignado')

df_limpio['resultado'] = df_limpio['resultado'].fillna('Sin evaluar')

print("VALORES COMPLETADOS: ------------")

print(df_limpio[['curso', 'resultado']].head(7))

VALORES COMPLETADOS: ------------
                      curso    resultado
0            Excel Avanzado     Aprobado
1     Comunicación Efectiva     Aprobado
2                 Liderazgo    Reprobado
3         Trabajo En Equipo  Sin evaluar
4                  Power Bi     Aprobado
5        Gestión Del Tiempo     Aprobado
6  Resolución De Conflictos    Reprobado

In [ ]:
#ELIMINAR DUPLICADOS

print(f"Duplicados antes: {df_limpio.duplicated().sum()}")

df_limpio = df_limpio.drop_duplicates().reset_index(drop=True)

print(f"Duplicados después: {df_limpio.duplicated().sum()}")

print(f"Nuevas dimensiones: {df_limpio.shape}")

Duplicados antes: 1
Duplicados después: 0
Nuevas dimensiones: (10, 16)

In [ ]:
#CONVERTIR COLUMNAS NUMÉRICAS

columnas_numericas = [
    'edad', 'desempeño', 'tiempo_empresa_anios', 'horas',
    'satisfaccion', 'horas_extra'
]

columnas_salarios = ['salario', 'salario_anual']

for columna in columnas_numericas:
    df_limpio[columna] = pd.to_numeric(df_limpio[columna], errors='coerce')

for columna in columnas_salarios:
    df_limpio[columna] = pd.to_numeric(df_limpio[columna], errors='coerce').astype(float)

print("Columnas numéricas convertidas: -------------")
print(df_limpio[columnas_numericas + columnas_salarios].dtypes)

Columnas numéricas convertidas: -------------
edad                      int64
desempeño                 int64
tiempo_empresa_anios      int64
horas                     int64
satisfaccion              int64
horas_extra               int64
salario                 float64
salario_anual           float64
dtype: object

In [ ]:
#CORREGIR SALARIOS NEGATIVOS

salarios_negativos = df_limpio[df_limpio['salario'] < 0]
print(f"Salarios negativos encontrados: {len(salarios_negativos)}")

if len(salarios_negativos) > 0:
  print(salarios_negativos[['id_empleado', 'salario', 'salario_anual']])

df_limpio['salario'] = df_limpio['salario'].abs()
df_limpio['salario_anual'] = df_limpio['salario_anual'].abs()

print("Salarios negativos corregidos")

Salarios negativos encontrados: 1
   id_empleado  salario  salario_anual
2            3   -650.0         7800.0
Salarios negativos corregidos

In [ ]:
#RECALCULAR VARIABLES DERIVADAS

df_limpio['salario_anual'] = df_limpio['salario'] * 12

df_limpio['salario_por_hora'] = df_limpio['salario'] / df_limpio['horas']

print("Variables recalculadas: -----")
print(df_limpio[['id_empleado', 'salario', 'horas', 'salario_anual', 'salario_por_hora']].head())

Variables recalculadas: -----
   id_empleado  salario  horas  salario_anual  salario_por_hora
0            1    550.0     10         6600.0         55.000000
1            2    900.0      8        10800.0        112.500000
2            3    650.0     12         7800.0         54.166667
3            4    750.0      6         9000.0        125.000000
4            5    700.0     10         8400.0         70.000000

In [ ]:
#CARACTERISTICAS TEMPORALES
#ANTIGÜEDAD

df_limpio['anios_redondeados'] = df_limpio['tiempo_empresa_anios'].round()

df_limpio['es_antiguo'] = df_limpio['tiempo_empresa_anios'] >= 5

def asignar_categoria(anios):
    if anios >= 5:
        return 'Senior'
    else:
        return 'Junior'


df_limpio['categoria_antiguedad'] = df_limpio['tiempo_empresa_anios'].apply(asignar_categoria)

def asignar_rango_edad(edad):
    if edad < 30: return 'Joven (<30)'
    elif edad <= 50: return 'Adulto (30-50)'
    else: return 'Mayor (>50)'

df_limpio['rango_edad'] = df_limpio['edad'].apply(asignar_rango_edad)

df_limpio['requiere_capacitacion'] = df_limpio['resultado'] == 'Reprobado'


print("Características de antigüedad creadas: -----")
print(df_limpio[['id_empleado', 'tiempo_empresa_anios', 'anios_redondeados', 'es_antiguo', 'categoria_antiguedad', 'rango_edad', 'requiere_capacitacion']].head())

In [ ]:
# REPORTE DE CALIDAD

reporte_calidad = pd.DataFrame({
    'columna': df_limpio.columns,
    'tipo_dato': [str(df_limpio[col].dtype) for col in df_limpio.columns],
    'valores_nulos': [df_limpio[col].isnull().sum() for col in df_limpio.columns],
    'valores_unicos': [df_limpio[col].nunique() for col in df_limpio.columns]
})

print("REPORTE CALIDAD")
reporte_calidad

REPORTE CALIDAD

                 columna tipo_dato  valores_nulos  valores_unicos
0            id_empleado     int64              0              10
1                 nombre    string              0              10
2           departamento    string              0               5
3                   edad     int64              0              10
4              desempeño     int64              0              10
5                salario   float64              0              10
6   tiempo_empresa_anios     int64              0               8
7        estado_empleado    string              0               2
8          salario_anual   float64              0              10
9        id_capacitacion     int64              0              10
10                 curso    string              0              10
11                 horas     int64              0               4
12             resultado    string              0               3
13    horas_capacitacion     int64              0               4
14          satisfaccion     int64              0               4
15           horas_extra     int64              0               8
16      salario_por_hora   float64              0              10
17     anios_redondeados     int64              0               8
18            es_antiguo      bool              0               2
19  categoria_antiguedad    object              0               2

In [ ]:
#GUARDAR REPORTE EN EXCEL
ruta_reporte = DOCUMENTOS / "reporte_calidad_HRTech_People_Analytics.xlsx"
reporte_calidad.to_excel(ruta_reporte, index=False)
print(f"Reporte guardado: {ruta_reporte}")

Reporte guardado: /content/documentos/reporte_calidad_HRTech_People_Analytics.xlsx

In [ ]:
# GUARDAR DATASET LIMPIO
ruta_salida = DATA_PROCESSED / "dataset_limpio_HRTech_People_Analytics.csv"
df_limpio.to_csv(ruta_salida, index=False, encoding='utf-8')
print(f"Dataset limpio guardado: {ruta_salida}")

Dataset limpio guardado: /content/datos/procesados/dataset_limpio_HRTech_People_Analytics.csv

In [ ]:
print("----------------- Guia 03 -------------------")

In [ ]:
#INSTALAR PYSPARK

%pip install pyspark
print("Pyspark instalado")

In [ ]:
#IMPORTAR LIBRERIAS
from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.types import *
from pathlib import Path
import pandas as pd
import time

print("Librerias importadas---------------")

Librerias importadas---------------

In [ ]:
#CREAR SESION DE SPARK

spark = SparkSession.builder \
    .master("local[*]") \
    .appName("HRTech_PeopleAnalytics_Arquitectura") \
    .getOrCreate()

print(f"Spark version: {spark.version}")
print(f"Paralelismo: {spark.sparkContext.defaultParallelism}")

Spark version: 4.0.4
Paralelismo: 2

In [ ]:
#DEFINIR RUTAS

BASE_DIR = Path("/content")
DATA_PROCESSED = BASE_DIR / "datos" / "procesados"
DATA_ANALYTICS = BASE_DIR / "datos" / "analiticos"
DOCUMENTOS = BASE_DIR / "documentos"

DATA_PROCESSED.mkdir(parents=True, exist_ok=True)
DATA_ANALYTICS.mkdir(parents=True, exist_ok=True)
DOCUMENTOS.mkdir(parents=True, exist_ok=True)

print(f"Datos procesados: {DATA_PROCESSED}")
print(f"Datos analiticos: {DATA_ANALYTICS}")
print(f"Documentos: {DOCUMENTOS}")

Datos procesados: /content/datos/procesados
Datos analiticos: /content/datos/analiticos
Documentos: /content/documentos

In [ ]:
#CARGAR DATASET LIMPIO
ruta_entrada = DATA_PROCESSED / "dataset_limpio_HRTech_People_Analytics.csv"

print(f"Leyendo: {ruta_entrada}")

df = spark.read \
    .option("header", True) \
    .option("inferSchema", True) \
    .csv(str(ruta_entrada))

print("Dataset cargado en Spark")
print(f"Filas: {df.count()}")
print(f"Columnas: {len(df.columns)}")

Leyendo: /content/datos/procesados/dataset_limpio_HRTech_People_Analytics.csv
Dataset cargado en Spark
Filas: 10
Columnas: 20

In [ ]:
#1. EXPLORACION BASICA - ESQUEMA Y ESTRUCTURA DEL DATASET
print("Esquema de datos:-------------")
df.printSchema()

print("\nPrimeras filas: ")
df.show(10, truncate=False)

Esquema de datos:-------------
root
 |-- id_empleado: integer (nullable = true)
 |-- nombre: string (nullable = true)
 |-- departamento: string (nullable = true)
 |-- edad: integer (nullable = true)
 |-- desempeño: integer (nullable = true)
 |-- salario: double (nullable = true)
 |-- tiempo_empresa_anios: integer (nullable = true)
 |-- estado_empleado: string (nullable = true)
 |-- salario_anual: double (nullable = true)
 |-- id_capacitacion: integer (nullable = true)
 |-- curso: string (nullable = true)
 |-- horas: integer (nullable = true)
 |-- resultado: string (nullable = true)
 |-- horas_capacitacion: integer (nullable = true)
 |-- satisfaccion: integer (nullable = true)
 |-- horas_extra: integer (nullable = true)
 |-- salario_por_hora: double (nullable = true)
 |-- anios_redondeados: integer (nullable = true)
 |-- es_antiguo: boolean (nullable = true)
 |-- categoria_antiguedad: string (nullable = true)


Primeras filas:
+-----------+------+------------+----+---------+-------+--------------------+---------------+-------------+---------------+------------------------+-----+-----------+------------------+------------+-----------+------------------+-----------------+----------+--------------------+
|id_empleado|nombre|departamento|edad|desempeño|salario|tiempo_empresa_anios|estado_empleado|salario_anual|id_capacitacion|curso                   |horas|resultado  |horas_capacitacion|satisfaccion|horas_extra|salario_por_hora  |anios_redondeados|es_antiguo|categoria_antiguedad|
+-----------+------+------------+----+---------+-------+--------------------+---------------+-------------+---------------+------------------------+-----+-----------+------------------+------------+-----------+------------------+-----------------+----------+--------------------+
|1          |Ana   |Ventas      |25  |85       |550.0  |2                   |Activo         |6600.0       |1              |Excel Avanzado          |10   |Aprobado   |10                |4           |5          |55.0              |2                |false     |Junior              |
|2          |Luis  |IT          |31  |92       |900.0  |5                   |Activo         |10800.0      |2              |Comunicación Efectiva   |8    |Aprobado   |8                 |5           |3          |112.5             |5                |true      |Senior              |
|3          |Carlos|Finanzas    |28  |70       |650.0  |1                   |Inactivo       |7800.0       |3              |Liderazgo               |12   |Reprobado  |12                |2           |12         |54.166666666666664|1                |false     |Junior              |
|4          |María |RRHH        |35  |88       |750.0  |7                   |Activo         |9000.0       |4              |Trabajo En Equipo       |6    |Sin evaluar|6                 |4           |4          |125.0             |7                |true      |Senior              |
|5          |Sofía |Marketing   |29  |78       |700.0  |3                   |Activo         |8400.0       |5              |Power Bi                |10   |Aprobado   |10                |3           |8          |70.0              |3                |false     |Junior              |
|6          |José  |IT          |26  |95       |950.0  |2                   |Activo         |11400.0      |6              |Gestión Del Tiempo      |6    |Aprobado   |6                 |5           |2          |158.33333333333334|2                |false     |Junior              |
|7          |Laura |Ventas      |40  |65       |600.0  |10                  |Inactivo       |7200.0       |7              |Resolución De Conflictos|8    |Reprobado  |8                 |2           |14         |75.0              |10               |true      |Senior              |
|8          |Daniel|Finanzas    |33  |82       |800.0  |6                   |Activo         |9600.0       |8              |Inteligencia Emocional  |8    |Aprobado   |8                 |4           |5          |100.0             |6                |true      |Senior              |
|9          |Paola |RRHH        |27  |90       |720.0  |2                   |Activo         |8640.0       |9              |Análisis De Datos       |12   |Aprobado   |12                |5           |3          |60.0              |2                |false     |Junior              |
|10         |Miguel|Marketing   |38  |74       |680.0  |8                   |Inactivo       |8160.0       |10             |Seguridad Informática   |10   |Aprobado   |10                |3           |9          |68.0              |8                |true      |Senior              |
+-----------+------+------------+----+---------+-------+--------------------+---------------+-------------+---------------+------------------------+-----+-----------+------------------+------------+-----------+------------------+-----------------+----------+--------------------+

In [ ]:
#ESTADISTICAS DESCRIPTIVAS
print("Estadisticas descriptivas (describe):-------------")
df.describe().show(truncate=False)

#ESTADISTICAS SOLO DE COLUMNAS NUMERICAS CLAVE
print("\nEstadisticas de columnas clave:")
df.describe("edad", "desempeño", "salario", "satisfaccion", "tiempo_empresa_anios").show(truncate=False)

Estadisticas descriptivas (describe):-------------
+-------+------------------+------+------------+-----------------+-----------------+------------------+--------------------+---------------+------------------+------------------+-----------------+------------------+-----------+------------------+------------------+-----------------+------------------+-----------------+--------------------+
|summary|id_empleado       |nombre|departamento|edad             |desempeño        |salario           |tiempo_empresa_anios|estado_empleado|salario_anual     |id_capacitacion   |curso            |horas             |resultado  |horas_capacitacion|satisfaccion      |horas_extra      |salario_por_hora  |anios_redondeados|categoria_antiguedad|
+-------+------------------+------+------------+-----------------+-----------------+------------------+--------------------+---------------+------------------+------------------+-----------------+------------------+-----------+------------------+------------------+-----------------+------------------+-----------------+--------------------+
|count  |10                |10    |10          |10               |10               |10                |10                  |10             |10                |10                |10               |10                |10         |10                |10                |10               |10                |10               |10                  |
|mean   |5.5               |NULL  |NULL        |31.2             |81.9             |730.0             |4.6                 |NULL           |8760.0            |5.5               |NULL             |9.0               |NULL       |9.0               |3.7               |6.5              |87.8              |4.6              |NULL                |
|stddev |3.0276503540974917|NULL  |NULL        |5.159672685570493|9.949316001057001|125.52113589175153|3.062315754094894   |NULL           |1506.2536307010184|3.0276503540974917|NULL             |2.1602468994692865|NULL       |2.1602468994692865|1.1595018087284057|4.089281382128433|34.91310200136941 |3.062315754094894|NULL                |
|min    |1                 |Ana   |Finanzas    |25               |65               |550.0             |1                   |Activo         |6600.0            |1                 |Análisis De Datos|6                 |Aprobado   |6                 |2                 |2                |54.166666666666664|1                |Junior              |
|max    |10                |Sofía |Ventas      |40               |95               |950.0             |10                  |Inactivo       |11400.0           |10                |Trabajo En Equipo|12                |Sin evaluar|12                |5                 |14               |158.33333333333334|10               |Senior              |
+-------+------------------+------+------------+-----------------+-----------------+------------------+--------------------+---------------+------------------+------------------+-----------------+------------------+-----------+------------------+------------------+-----------------+------------------+-----------------+--------------------+


Estadisticas de columnas clave:
+-------+-----------------+-----------------+------------------+------------------+--------------------+
|summary|edad             |desempeño        |salario           |satisfaccion      |tiempo_empresa_anios|
+-------+-----------------+-----------------+------------------+------------------+--------------------+
|count  |10               |10               |10                |10                |10                  |
|mean   |31.2             |81.9             |730.0             |3.7               |4.6                 |
|stddev |5.159672685570493|9.949316001057001|125.52113589175153|1.1595018087284057|3.062315754094894   |
|min    |25               |65               |550.0             |2                 |1                   |
|max    |40               |95               |950.0             |5                 |10                  |
+-------+-----------------+-----------------+------------------+------------------+--------------------+

In [ ]:
#PARTICIONES - CON SPARK
print("Particiones iniciales:", df.rdd.getNumPartitions())

Particiones iniciales: 1

In [ ]:
#TRANSFORMACION 1 - FILTER: EMPLEADOS ACTIVOS
df_activos = df.filter(F.col("estado_empleado") == "Activo")

print(f"Registros totales: {df.count()}")
print(f"Empleados activos: {df_activos.count()}")
print(f"Empleados inactivos: {df.count() - df_activos.count()}")

df_activos.select("id_empleado", "nombre", "departamento", "estado_empleado").show(truncate=False)

Registros totales: 10
Empleados activos: 7
Empleados inactivos: 3
+-----------+------+------------+---------------+
|id_empleado|nombre|departamento|estado_empleado|
+-----------+------+------------+---------------+
|1          |Ana   |Ventas      |Activo         |
|2          |Luis  |IT          |Activo         |
|4          |María |RRHH        |Activo         |
|5          |Sofía |Marketing   |Activo         |
|6          |José  |IT          |Activo         |
|8          |Daniel|Finanzas    |Activo         |
|9          |Paola |RRHH        |Activo         |
+-----------+------+------------+---------------+

In [ ]:
#TRANSFORMACION 2 - WITHCOLUMN: COLUMNA DERIVADA
#BONO ESTIMADO = SALARIO * (DESEMPEÑO / 100) * 0.10

df_enriquecido = df_activos.withColumn(
    "bono_estimado",
    F.round(F.col("salario") * (F.col("desempeño") / 100) * 0.10, 2)
)

print("Columna 'bono_estimado' creada---------------------")
df_enriquecido.select("id_empleado", "nombre", "salario", "desempeño", "bono_estimado").show(truncate=False)

In [ ]:
#TRANSFORMACION 3 - GROUPBY + ORDERBY: RESUMEN POR DEPARTAMENTO

resumen_departamento = df_activos.groupBy("departamento").agg(
    F.round(F.avg("salario"), 2).alias("salario_promedio"),
    F.round(F.avg("desempeño"), 2).alias("desempeño_promedio"),
    F.round(F.avg("satisfaccion"), 2).alias("satisfaccion_promedio"),
    F.count("*").alias("cantidad_empleados")
).orderBy(F.desc("salario_promedio"))

print("Resumen por departamento----------------")
resumen_departamento.show(truncate=False)

In [ ]:
#TRANSFORMACION 4 - GROUPBY + ORDERBY: RESUMEN POR CATEGORIA DE ANTIGÜEDAD

resumen_antiguedad = df_activos.groupBy("categoria_antiguedad").agg(
    F.count("*").alias("cantidad_empleados"),
    F.round(F.avg("horas_extra"), 2).alias("horas_extra_promedio")
).orderBy(F.desc("cantidad_empleados"))

print("Resumen por categoria de antiguedad----------------")
resumen_antiguedad.show(truncate=False)

In [ ]:
#TRANSFORMACION 5 - JOIN CON TABLA DE DIMENSION (NIVEL DE PRIORIDAD POR DEPARTAMENTO)

departamentos_prioridad = [
    ("Ventas", "Comercial", "Alto"),
    ("IT", "Tecnologia", "Alto"),
    ("Finanzas", "Administrativo", "Medio"),
    ("RRHH", "Administrativo", "Medio"),
    ("Marketing", "Comercial", "Alto"),
]

df_prioridad = spark.createDataFrame(
    departamentos_prioridad, ["departamento", "area", "nivel_prioridad"]
)

print("Tabla de prioridad por departamento: -----------------")
df_prioridad.show()

df_con_prioridad = df_enriquecido.join(df_prioridad, on="departamento", how="left")
print(f"Filas antes: {df_enriquecido.count()}")
print(f"Filas despues: {df_con_prioridad.count()}")

print("Datos con area y nivel de prioridad: ----------")
df_con_prioridad.select(
    "id_empleado", "nombre", "departamento", "area", "nivel_prioridad", "bono_estimado"
).orderBy(F.desc("bono_estimado")).show(10, truncate=False)

In [ ]:
#CREAR VISTA TEMPORAL
df_con_prioridad.createOrReplaceTempView("empleados_analiticos")
print("Vista temporal 'empleados_analiticos' creada")

In [ ]:
#CONSULTA SQL - RESUMEN POR DEPARTAMENTO Y NIVEL DE PRIORIDAD

consulta = """
    SELECT
        departamento,
        area,
        nivel_prioridad,
        COUNT(*) AS cantidad_empleados,
        ROUND(AVG(salario), 2) AS salario_promedio,
        ROUND(AVG(`desempeño`), 2) AS desempeno_promedio,
        ROUND(SUM(bono_estimado), 2) AS bono_total
    FROM empleados_analiticos
    GROUP BY departamento, area, nivel_prioridad
    ORDER BY salario_promedio DESC
"""

resultado_sql = spark.sql(consulta)
print("CONSULTA SQL - RESUMEN POR DEPARTAMENTO -----------------")
resultado_sql.show(truncate=False)

In [ ]:
#SEGUNDA CONSULTA SQL - EMPLEADOS CON MEJOR DESEMPEÑO

consulta_top = """
    SELECT nombre, departamento, `desempeño`, satisfaccion, bono_estimado
    FROM empleados_analiticos
    ORDER BY `desempeño` DESC
    LIMIT 5
"""

top_empleados = spark.sql(consulta_top)
print("CONSULTA SQL - TOP 5 EMPLEADOS POR DESEMPEÑO -----------------")
top_empleados.show(truncate=False)

In [ ]:
#VER PLAN DE EJECUCION

print("Plan de ejecucion formateado:----------------------")
resultado_sql.explain("formatted")

In [ ]:
#INSPECCIONAR PARTICIONES ACTUALES
print(f"Particiones actuales: {df_con_prioridad.rdd.getNumPartitions()}")

In [ ]:
#REPARTICIONAR EN 4

df_particionado = df_con_prioridad.repartition(4)
print(f"Nuevas particiones: {df_particionado.rdd.getNumPartitions()}")

In [ ]:
#GUARDAR EN PARQUET

ruta_parquet = DATA_ANALYTICS / "empleados_analiticos_parquet"

df_particionado.write \
    .mode("overwrite") \
    .parquet(str(ruta_parquet))

print(f"Parquet guardado en: {ruta_parquet}")

In [ ]:
#LEER PARQUET PARA VERIFICAR
df_leido = spark.read.parquet(str(ruta_parquet))

print(f"Filas leidas: {df_leido.count()}")
print("Primeras filas: -----------------")
df_leido.show(5, truncate=False)

In [ ]:
#AGREGACION CON PANDAS (CON MEDICION DE TIEMPO)

inicio_pd = time.perf_counter()

df_pd = pd.read_csv(DATA_PROCESSED / "dataset_limpio_HRTech_People_Analytics.csv")
pd_departamento = (
    df_pd[df_pd["estado_empleado"] == "Activo"]
    .groupby("departamento")["salario"]
    .mean()
    .round(2)
    .reset_index()
)
pd_departamento.columns = ["departamento", "salario_promedio_pandas"]

fin_pd = time.perf_counter()
tiempo_pandas = fin_pd - inicio_pd

print(f"Tiempo Pandas: {tiempo_pandas:.4f} segundos")
print("Pandas - salario promedio por departamento")
print(pd_departamento)

In [ ]:
#MISMA AGREGACION CON SPARK (CON MEDICION DE TIEMPO)

inicio_spark = time.perf_counter()

sp_departamento = (
    df_activos.groupBy("departamento")
    .agg(F.round(F.avg("salario"), 2).alias("salario_promedio_spark"))
    .orderBy("departamento")
    .toPandas()
)

fin_spark = time.perf_counter()
tiempo_spark = fin_spark - inicio_spark

print(f"Tiempo Spark: {tiempo_spark:.4f} segundos")
print("\nSpark - salario promedio por departamento")
print(sp_departamento)

In [ ]:
#COMPARAR RESULTADOS Y TIEMPOS

print("Comparacion Pandas vs Spark (resultados)")
comparacion = pd.merge(pd_departamento, sp_departamento, on="departamento")
print(comparacion)

print("\nComparacion de tiempos de ejecucion")
print(f"Pandas: {tiempo_pandas:.4f} s")
print(f"Spark:  {tiempo_spark:.4f} s")

if tiempo_pandas < tiempo_spark:
    diferencia = tiempo_spark / tiempo_pandas
    print(f"\nPandas fue {diferencia:.1f}x mas rapido que Spark en esta prueba.")
else:
    diferencia = tiempo_pandas / tiempo_spark
    print(f"\nSpark fue {diferencia:.1f}x mas rapido que Pandas en esta prueba.")

In [ ]:
#REPORTE DE ARQUITECTURA - GUIA 3 - PROYECTO HRTECH

print("\nREPORTE DE ARQUITECTURA - GUIA 3 - HRTECH PEOPLE ANALYTICS")
print("=" * 60)
print(f"Version de Spark: {spark.version}")
print(f"Dataset de entrada: dataset_limpio_HRTech_People_Analytics.csv")
print(f"Filas procesadas: {df_activos.count()}")
print(f"Columnas originales: {len(df.columns)}")
print(f"Columnas finales: {len(df_particionado.columns)}")
print(f"Particiones iniciales: {df.rdd.getNumPartitions()}")
print(f"Particiones finales: {df_particionado.rdd.getNumPartitions()}")
print(f"Salida Parquet: {ruta_parquet}")
print(f"Formato: Parquet")
print(f"Tiempo Pandas (agregacion): {tiempo_pandas:.4f} s")
print(f"Tiempo Spark (agregacion): {tiempo_spark:.4f} s")
print("=" * 60)

In [ ]:
# DESCARGAR PARQUET (ZIP automático)

!zip -r /content/empleados_analiticos_parquet.zip /content/  Datos/analiticos/empleados_analiticos_parquet/


from google.colab import files

files.download("/content/empleados_analiticos_parquet.zip")

print("Parquet descargado!")

In [ ]:
print("----------------- Guia 04 -------------------")

In [ ]:
  #IMPORTAR LIBRERIAS

import pandas as pd
import numpy as np
import hashlib
from pathlib import Path


print("Librerias importadas --------------")

In [ ]:
#CREAR CARPETAS PARA GOBERNANZA

BASE_DIR = Path("/content")
DATA_PROCESSED = BASE_DIR / "datos" / "procesados"
DATA_GOV = BASE_DIR / "datos" / "gobernanza"
DOCS_DIR = BASE_DIR / "documentos"

DATA_PROCESSED.mkdir(parents=True, exist_ok=True)
DATA_GOV.mkdir(parents=True, exist_ok=True)
DOCS_DIR.mkdir(parents=True, exist_ok=True)

print(f"Datos procesados: {DATA_PROCESSED}")
print(f"Datos gobernanza: {DATA_GOV}")
print(f"Documentos: {DOCS_DIR}")

In [ ]:
#CARGAR DATASET LIMPIO DE EMPLEADOS (GUIA 2)
ruta_entrada = DATA_PROCESSED / "dataset_limpio_HRTech_People_Analytics.csv"

empleados = pd.read_csv(ruta_entrada)

print("Dataset de empleados cargado --------------------")
print(f"Filas: {empleados.shape[0]}, Columnas: {empleados.shape[1]}")
empleados

In [ ]:
#CLASIFICACION DE DATOS DEL PROYECTO HRTECH
#NIVELES: PUBLICO, INTERNO, CONFIDENCIAL, RESTRINGIDO

clasificacion = pd.DataFrame([
    ["id_empleado",          "Identificador interno",     "Confidencial", "Vincular registros entre fuentes",        "Seudonimizar"],
    ["nombre",                "Identificador directo",     "Restringido",  "Contacto / identificacion humana",        "Enmascarar o excluir de vistas analiticas"],
    ["departamento",          "Organizacional",            "Interno",      "Segmentacion y analitica por area",       "Conservar"],
    ["edad",                  "Demografico",                "Confidencial", "Analisis demografico / antiguedad",       "Generalizar por rango"],
    ["desempeño",             "Evaluacion de desempeño",   "Restringido",  "Gestion de talento, bonos",                "Generalizar en categorias"],
    ["salario",                "Compensacion economica",    "Restringido",  "Analisis de compensacion",                "Generalizar por rango salarial"],
    ["salario_anual",          "Compensacion economica",    "Restringido",  "Analisis de compensacion",                "Generalizar por rango salarial"],
    ["salario_por_hora",       "Compensacion economica",    "Restringido",  "Analisis de compensacion",                "Generalizar por rango salarial"],
    ["tiempo_empresa_anios",   "Historial laboral",         "Interno",      "Antiguedad, retencion de talento",        "Conservar (agregado)"],
    ["estado_empleado",        "Estatus laboral",           "Confidencial", "Gestion de rotacion / bajas",             "Restringir acceso, usar en agregados"],
    ["id_capacitacion",        "Identificador interno",     "Interno",      "Vincular capacitaciones",                 "Conservar"],
    ["curso",                  "Formacion",                  "Interno",      "Analisis de capacitacion",                "Conservar"],
    ["horas",                  "Formacion",                  "Interno",      "Analisis de capacitacion",                "Conservar"],
    ["resultado",              "Evaluacion de formacion",   "Confidencial", "Seguimiento de aprendizaje",              "Conservar (agregado)"],
    ["horas_capacitacion",     "Formacion",                  "Interno",      "Analisis de capacitacion",                "Conservar"],
    ["satisfaccion",           "Bienestar / clima laboral",  "Confidencial", "Clima organizacional",                    "Generalizar en categorias"],
    ["horas_extra",            "Carga laboral",              "Interno",      "Analisis de carga de trabajo",            "Conservar (agregado)"],
    ["anios_redondeados",      "Historial laboral",         "Interno",      "Antiguedad",                               "Conservar"],
    ["es_antiguo",             "Historial laboral",         "Interno",      "Antiguedad",                               "Conservar"],
    ["categoria_antiguedad",   "Historial laboral",         "Interno",      "Segmentacion por antiguedad",             "Conservar"],
],
columns=["campo", "tipo", "clasificacion", "finalidad", "control"])

print("Matriz de clasificacion de campos -------------------------------")
clasificacion

In [ ]:
#GUARDAR CLASIFICACION
ruta_clasificacion = DOCS_DIR / "clasificacion_datos_HRTech_People_Analytics.xlsx"

clasificacion.to_excel(ruta_clasificacion, index=False)

print(f"Clasificacion guardada en: {ruta_clasificacion}")

In [ ]:
#TECNICA 1 - SEUDONIMIZACION: HASH DEL ID DE EMPLEADO

SALT = "hrtech-people-analytics-guia04"

def tokenizar(valor):
    """Convierte un valor en un codigo unico e irreversible de 12 caracteres."""
    texto = f"{SALT}|{valor}".encode("utf-8")
    return hashlib.sha256(texto).hexdigest()[:12]

empleados["empleado_token"] = empleados["id_empleado"].astype(str).apply(tokenizar)

print("Seudonimizacion aplicada --------------------")
empleados[["id_empleado", "nombre", "empleado_token"]]

In [ ]:
#TECNICA 2 - ENMASCARAMIENTO DEL NOMBRE

def enmascarar_nombre(nombre):
    """Muestra solo la primera letra del nombre."""
    nombre = str(nombre).strip()
    if len(nombre) == 0:
        return "***"
    return f"{nombre[0]}***"

empleados["nombre_mask"] = empleados["nombre"].apply(enmascarar_nombre)

print("Nombre enmascarado --------------------")
empleados[["nombre", "nombre_mask"]]

In [ ]:
#TECNICA 3 - GENERALIZACION DE EDAD POR RANGOS

bins_edad = [0, 24, 29, 34, 39, 44, 200]
labels_edad = ["<=24", "25-29", "30-34", "35-39", "40-44", "45+"]

empleados["rango_edad"] = pd.cut(empleados["edad"], bins=bins_edad, labels=labels_edad)

print("Edad generalizada ---------------------------")
empleados[["edad", "rango_edad"]]

In [ ]:
#TECNICA 4 - GENERALIZACION DE SALARIO Y DESEMPEÑO POR RANGOS/CATEGORIAS

bins_salario = [0, 600, 700, 800, 900, 100000]
labels_salario = ["<=600", "601-700", "701-800", "801-900", "901+"]
empleados["rango_salarial"] = pd.cut(empleados["salario"], bins=bins_salario, labels=labels_salario)

def categorizar_desempeño(valor):
    if valor >= 90:
        return "Excelente"
    elif valor >= 80:
        return "Bueno"
    elif valor >= 70:
        return "Regular"
    else:
        return "Bajo"

empleados["categoria_desempeño"] = empleados["desempeño"].apply(categorizar_desempeño)

print("Salario y desempeño generalizados ---------------------------")
empleados[["salario", "rango_salarial", "desempeño", "categoria_desempeño"]]

In [ ]:
#PRINCIPIO DE MINIMIZACION - VISTA ANALITICA PROTEGIDA

vista_analitica = empleados[[
    "empleado_token",
    "departamento",
    "rango_edad",
    "categoria_desempeño",
    "rango_salarial",
    "estado_empleado",
    "categoria_antiguedad",
    "satisfaccion",
    "horas_extra",
]].copy()

print("VISTA ANALITICA PROTEGIDA (SIN IDENTIFICADORES DIRECTOS NI VALORES EXACTOS)")
vista_analitica

In [ ]:
#GUARDAR VISTA PROTEGIDA
ruta_publicable = DATA_GOV / "dataset_publicable_HRTech_People_Analytics.csv"
vista_analitica.to_csv(ruta_publicable, index=False, encoding="utf-8")
print(f"Vista protegida guardada: {ruta_publicable}")

In [ ]:
#VALIDACION AUTOMATICA DE IDENTIFICADORES DIRECTOS

identificadores_directos = {"nombre", "correo", "telefono", "id_empleado", "salario", "edad", "desempeño"}
expuestos = identificadores_directos.intersection(vista_analitica.columns)

print("Verificando identificadores directos y valores exactos sensibles: -----------------")
print(f"Campos expuestos: {expuestos}")

if len(expuestos) == 0:
    print("Ningun identificador directo ni valor exacto sensible expuesto!!!!!")
else:
    print("ALERTA: hay campos sensibles expuestos!!!!!!!!")

In [ ]:
#MATRIZ DE RIESGOS - PROYECTO HRTECH PEOPLE ANALYTICS

riesgos = pd.DataFrame([
    ["Exposicion de identificadores directos (nombre)",              4, 5, "Enmascarar o excluir de vistas analiticas",           "Lider de datos / RRHH",     "Dataset protegido"],
    ["Filtracion de datos de compensacion (salario)",                 3, 5, "Generalizar por rango, cifrar en reposo",             "Administrador de sistemas", "Vista protegida + control de acceso"],
    ["Reidentificacion por combinacion de atributos (dept+edad+salario)", 3, 4, "Generalizar variables y revisar granularidad",  "Analista de datos",         "Analisis de grupos minimos (k-anonimidad)"],
    ["Acceso excesivo al dataset crudo de RRHH",                      3, 5, "Control de acceso basado en roles (RBAC)",            "Administrador",             "Matriz de acceso por rol"],
    ["Sesgo o discriminacion en decisiones basadas en desempeño",     3, 5, "Revision etica de modelos/criterios de evaluacion",   "Equipo analitico / RRHH",   "Auditoria de criterios"],
    ["Uso de datos de satisfaccion para acciones punitivas",          2, 5, "Politica de uso agregado, no individual",             "Direccion de RRHH",         "Politica de uso"],
    ["Retencion indefinida de datos de exempleados",                  3, 3, "Regla de retencion y eliminacion",                    "Lider de proyecto",         "Bitacora de eliminacion"],
    ["Uso del dato para finalidad no definida originalmente",         2, 4, "Registrar y limitar el proposito del dato",           "Propietario del dato",      "Ficha de finalidad"],
],
columns=["riesgo", "probabilidad", "impacto", "control", "responsable", "evidencia"])

riesgos["puntaje"] = riesgos["probabilidad"] * riesgos["impacto"]
riesgos["nivel"] = riesgos["puntaje"].apply(
    lambda x: "Critico" if x >= 16 else "Alto" if x >= 10 else "Moderado" if x >= 5 else "Bajo"
)

print("MATRIZ DE RIESGOS:")
riesgos.sort_values("puntaje", ascending=False)

In [ ]:
#GUARDAR LA MATRIZ DE RIESGOS
ruta_riesgos = DOCS_DIR / "matriz_riesgos_HRTech_People_Analytics.xlsx"
riesgos.to_excel(ruta_riesgos, index=False)
print(f"Matriz de riesgos guardada -------------------- {ruta_riesgos}")

In [ ]:
# POLITICA DE GOBERNANZA - PROYECTO HRTECH PEOPLE ANALYTICS

politica = """
# Politica de Gobernanza de Datos - HRTech People Analytics

## 1. Proposito
Definir como se usan, protegen, comparten y eliminan los datos de empleados
del proyecto HRTech People Analytics, minimizando el riesgo de exposicion
indebida de informacion personal, de desempeno y de compensacion.

## 2. Clasificacion de los datos
- **Publico**: agregados generales sin posibilidad de reidentificacion
  (ej. numero total de empleados por departamento).
- **Interno**: uso dentro del equipo de People Analytics
  (departamento, antiguedad, horas de capacitacion, horas extra).
- **Confidencial**: requiere proteccion y justificacion de uso
  (id_empleado, edad, estado_empleado, resultado de evaluaciones, satisfaccion).
- **Restringido**: acceso limitado a roles autorizados unicamente
  (nombre, salario, salario_anual, salario_por_hora, desempeño).

## 3. Acceso por rol
- **Administrador de RRHH**: acceso total al dataset crudo (identificado),
  bajo justificacion de negocio y registro de auditoria.
- **Analista de People Analytics**: acceso unicamente a la **vista
  analitica protegida** (`dataset_publicable_HRTech_People_Analytics.csv`),
  sin identificadores directos ni valores exactos de salario/edad/desempeño.
- **Auditor / Comite de etica**: acceso de solo lectura a la evidencia de
  gobernanza (clasificacion, matriz de riesgos, bitacoras), no a los datos
  crudos.
- **Empleado (titular del dato)**: derecho a solicitar que informacion
  personal propia le sea mostrada o corregida, conforme a los principios de
  transparencia.

## 4. Minimizacion
Solo se incluyen en la vista analitica los campos estrictamente necesarios
para los analisis de RRHH (rotacion, desempeño agregado, clima laboral,
capacitacion). Los identificadores directos y los valores exactos de
variables Restringidas se sustituyen por tokens, mascaras o rangos antes de
compartir cualquier dataset fuera del equipo de Administracion.

## 5. Retencion
- Datos de empleados **activos**: se conservan mientras dure la relacion
  laboral, mas el periodo minimo exigido por la normativa laboral/fiscal
  aplicable.
- Datos de empleados **inactivos**: se conservan un maximo definido por
  politica interna (ej. 2 anios) y luego se anonimizan o eliminan,
  salvo obligacion legal de conservarlos.
- Vistas analiticas protegidas: se regeneran a partir del dataset crudo
  cuando se requieran; no se mantienen copias antiguas sin control de
  version.

## 6. Etica
- No se toman decisiones automatizadas de contratacion, despido o ascenso
  basadas unicamente en los datos de este proyecto sin revision humana.
- No se usan variables sensibles (edad, salario, desempeño) para generar
  perfiles individuales fuera del proposito declarado de People Analytics.
- Las conclusiones se presentan siempre de forma agregada (por
  departamento, rango, categoria) y nunca senalando a un empleado en
  particular en reportes de uso general.
- Se revisa periodicamente que los criterios de evaluacion de desempeño no
  generen sesgos hacia algun departamento, rango de edad o antiguedad.
"""

print("Politica de gobernanza redactada --------------------")
print(politica[:400], "...")

In [ ]:
#GUARDAR POLITICA
ruta_politica = DOCS_DIR / "politica_gobernanza_HRTech_People_Analytics.md"
with open(ruta_politica, "w", encoding="utf-8") as f:
    f.write(politica)

print(f"Politica guardada: {ruta_politica}")

In [ ]:
#VERIFICAR ARCHIVOS GENERADOS
import subprocess

print("----------- ARCHIVOS GENERADOS ------------")
print("=" * 50)
!ls -la /content/datos/gobernanza/

print("\n----------- ARCHIVOS GENERADOS: DOCUMENTOS ------------")
print("=" * 50)
!ls -la /content/documentos/